Version 1.0.0
HealthDataInsight/way_of_working-changelog-keepachangelog pull request #1
Opened 2024-10-29 15:55 UTC by timgentry

## What?

I've moved the keepachangelog template that was built into the Way of Working version 1 into a plugin for version 2.

## Why?

The Way of Working has been updated to be agnostic of the tooling it uses, therefore all the pre-existing tools need to be moved into plugins. This is the plugin for the keepachangelog changeling template.

## How?

This uses a boilerplate plugin and adds the code that existed in v1 of the WoW, with minor changes to the namespacing for plugins.

## Testing?

This includes tests and has been shown to work as a plugin.

## Anything Else?

A separate PR will be needed to audit for code safety.

2024-11-04 21:20 UTC, ollietulloch commented on README.md
> +> * Mention whether you follow Semantic Versioning.
Is this something we could enforce, i.e. everything should follow semantic versioning?

2025-01-23 17:34 UTC, timgentry commented on README.md
> +> * Mention whether you follow Semantic Versioning.
How might we enforce semver @ollietulloch?

2025-01-24 07:39 UTC, ollietulloch commented on README.md
> +> * Mention whether you follow Semantic Versioning.
Could we use [semantic-release](https://github.com/semantic-release/semantic-release) to determine the expected semantic version and compare that against the suggested version by the user?

Or perhaps include something in a github [action](https://github.com/marketplace/actions/git-semantic-version)?

Both ways feel a bit fiddly.

2025-01-24 16:37 UTC, timgentry commented on README.md
> +> * Mention whether you follow Semantic Versioning.
Perhaps that is something for v1.1?

2025-01-24 17:44 UTC, timgentry commented on README.md
> +> * Mention whether you follow Semantic Versioning.
@ollietulloch I'm keen that people can adopt server without having to adopt keepachangelog. Therefore we should create a new `way_of_working-versioning-semantic_versioning` plugin (which only deals with enforcing semver) and then make that a dependency of this plugin.

2025-01-28 18:29 UTC, ollietulloch commented on README.md
> +> * Mention whether you follow Semantic Versioning.
Good point, we shouldn't enforce keepachangelog

2025-06-04 09:41 UTC, timgentry commented
@ollietulloch could you approve this when you get time, thanks

2025-10-21 16:27 UTC, shilpigoeldev requested changes

2025-10-21 16:27 UTC, shilpigoeldev commented on lib/way_of_working/changelog/keepachangelog/generators/init.rb
> +        # This class fetches the CODE_OF_CONDUCT.md and inserts the contact method
should be CHANGELOG.md

2025-10-21 16:27 UTC, shilpigoeldev commented on test/way_of_working/audit_github_stub_classes.rb
> +          def initialize(client, repo_name)
doesn't match initialize method of base class

2025-10-23 19:47 UTC, shilpigoeldev approved these changes

2025-10-24 07:59 UTC, merged